export const CITIES_SET_CITIES = 'CITIES_SET_CITIES';
export const CITIES_SET_CITY = 'CITIES_SET_CITY';
export const CITIES_CLEAR_DATA = 'CITIES_CLEAR_DATA';
export const CITIES_SET_IS_FETCHING = 'CITIES_SET_IS_FETCHING';
export const CITIES_SET_SEARCH = 'CITIES_SET_SEARCH';
