export const RESTAURANTS_SET_RESTAURANTS = 'RESTAURANTS_SET_RESTAURANTS';
export const RESTAURANTS_SET_SAVED_RESTAURANTS = 'RESTAURANTS_SET_SAVED_RESTAURANTS';
export const RESTAURANTS_CLEAR_DATA = 'RESTAURANTS_CLEAR_DATA';
